### PR TITLE
Scaffold: Added security disclosure policy

### PR DESCRIPTION
**Pull request by sttk**
This PR is to complete a Tidelift task.

### CODE REVIEW

**Comment by phated** [comment]
@sttk don't merge things automatically. This isn't necessary because we have organization security notice.

**Comment by sttk** [comment]
@phated Sorry for merging automatically.

About `security.md`, this file is requested by Tidelift as a task.

**Comment by phated** [comment]
@sttk No, it is a bug in tidelift, Tidelift reads the **global** security policy at https://github.com/gulpjs/.github/blob/master/SECURITY.md - if they have a bug, you need to report it to them, not push into gulp repos.

**Comment by sttk** [comment]
@phated I entered the above URL as security policy page for Tidelift, and it succeeded. This pr was my mistake.
Is it better to change security policy pages of other packages to the above?

**Comment by phated** [comment]
Yes, all should use the global policy

**Comment by sttk** [comment]
OK, I'll do that. Thanks.

**Pull request merged**
