### PR TITLE
Add JSCS to repo

### PR DESCRIPTION
**Pull request by pdehaan**
```sh
$ npm run lint

> vinyl@1.0.0 lint /Users/pdehaan/dev/github/vinyl
> jshint *.js lib/ test/ && jscs *.js lib/ test/

$ echo $?
0
```

### CODE REVIEW

**Comment by phated** [comment]
@pdehaan how many comments would need to be changed?  I'd prefer to leave that rule on if it isn't many and just change the comments

**Comment by pdehaan** [comment]
@phated: TL;DR: 13

---

```sh
$ cat .jscsrc
{
  "preset": "gulp"
}

$ npm run lint

> vinyl@1.0.0 lint /Users/pdehaan/dev/github/vinyl
> jshint *.js lib/ test/ && jscs *.js lib/ test/

Comments must start with an uppercase letter, unless it is part of a textblock at index.js :
    15 |  }
    16 |
    17 |  // record path change
----------^
    18 |  var history = file.path ? [file.path] : file.history;
    19 |  this.history = history || [];

Comments must start with an uppercase letter, unless it is part of a textblock at index.js :
    22 |  this.base = file.base || this.cwd;
    23 |
    24 |  // stat = files stats object
----------^
    25 |  this.stat = file.stat || null;
    26 |

Comments must start with an uppercase letter, unless it is part of a textblock at index.js :
    25 |  this.stat = file.stat || null;
    26 |
    27 |  // contents = stream, buffer, or null if not read
----------^
    28 |  this.contents = file.contents || null;
    29 |

Comments must start with an uppercase letter, unless it is part of a textblock at index.js :
    64 |  }
    65 |
    66 |  // clone our file contents
----------^
    67 |  var contents;
    68 |  if (this.isStream()) {

Comments must start with an uppercase letter, unless it is part of a textblock at index.js :
    81 |  });
    82 |
    83 |  // clone our custom properties
----------^
    84 |  Object.keys(this).forEach(function(key) {
    85 |    // ignore built-in fields

Comments must start with an uppercase letter, unless it is part of a textblock at index.js :
    83 |  // clone our custom properties
    84 |  Object.keys(this).forEach(function(key) {
    85 |    // ignore built-in fields
------------^
    86 |    if (key === '_contents' || key === 'stat' ||
    87 |      key === 'history' || key === 'path' ||

Comments must start with an uppercase letter, unless it is part of a textblock at index.js :
   114 |  }
   115 |
   116 |  // isNull
----------^
   117 |  if (opt.end) {
   118 |    stream.end();

Comments must start with an uppercase letter, unless it is part of a textblock at index.js :
   124 |  var inspect = [];
   125 |
   126 |  // use relative path if possible
----------^
   127 |  var filePath = (this.base && this.path) ? this.relative : this.path;
   128 |

Comments must start with an uppercase letter, unless it is part of a textblock at index.js :
   146 |};
   147 |
   148 |// virtual attributes
--------^
   149 |// or stuff with extra logic
   150 |Object.defineProperty(File.prototype, 'contents', {

Comments must start with an uppercase letter, unless it is part of a textblock at index.js :
   230 |    }
   231 |
   232 |    // record history only when path changed
------------^
   233 |    if (path && path !== this.path) {
   234 |      this.history.push(path);

Comments must start with an uppercase letter, unless it is part of a textblock at lib/inspectStream.js :
     7 |
     8 |  var streamType = stream.constructor.name;
     9 |  // avoid StreamStream
----------^
    10 |  if (streamType === 'Stream') {
    11 |    streamType = '';

Comments must start with an uppercase letter, unless it is part of a textblock at test/File.js :
   878 |      file.history.should.eql(['/test/test.coffee']);
   879 |
   880 |      // ignore when set empty string
--------------^
   881 |      file.path = '';
   882 |      file.path.should.eql('/test/test.coffee');

Comments must start with an uppercase letter, unless it is part of a textblock at test/cloneBuffer.js :
    18 |    var testBuffer2 = cloneBuffer(testBuffer);
    19 |
    20 |    // test that changes dont modify both pointers
------------^
    21 |    testBuffer2.write('w');
    22 |


13 code style errors found.
```

**Comment by phated** [comment]
Cool. Mind updating those?

**Comment by pdehaan** [comment]
Done.

**Comment by phated** [comment]
Thanks!

**Pull request merged**
