### PR TITLE
File.stem for basename without suffix

### PR DESCRIPTION
**Pull request by soslan**
Hello!
This patch adds `stem` property to `File` for getting and setting filename part preceding the last period (sometimes also called basename[1]).

[1] https://www.gnu.org/software/make/manual/html_node/File-Name-Functions.html

### CODE REVIEW

**Comment by kevva** [comment]
You could just use https://github.com/hparra/gulp-rename.

**Comment by soslan** [comment]
I see in gulp-rename, basename means filename without the suffix, while here, basename is effectively the whole filename.

**Comment by soslan** [comment]
@kevva You still have to gulp.dest() it. Handling names in gulp.dest() is more concise, IMO.

**Comment by phated** [comment]
In node, basename is both with and without extension.  See https://nodejs.org/api/path.html#path_path_basename_p_ext

I'm not sure about adding this.

**Comment by sindresorhus** [comment]
:+1: 

@phated But to do so with the Node.js API you need to know the extension, which means you'll end up with something like this: `path.basename(filepath, path.extname(filepath))` which is very verbose. I wish the Node.js API had a stem method too.

**Comment by phated** [comment]
@sindresorhus okay, what is the best name for this?  The linked document doesn't mention "stem"

**Comment by sindresorhus** [comment]
PHP [uses](http://de.php.net/manual/en/function.pathinfo.php) `filename` for `basename` without extension.

**Comment by phated** [comment]
Looks like C++ calls it a stem

**Comment by phated** [comment]
So does python and rust.  Probably stick with stem then.

**Comment by sindresorhus** [comment]
I prefer stem too.

**Comment by phated** [comment]
@soslan This looks to be failing the updated linting/jscs rules.  Can you update this PR?  Everything else looks good.

**Comment by soslan** [comment]
@phated  Done. I should have not synced it with upstream though.

**Comment by phated** [comment]
Published as 1.1.0 - Thanks for this feature!

**Comment by gilly3** [comment]
I want this in gulp ^3.9.0. Can we merge this into a vinyl v0.* release?  Or update gulp 3 to use vinyl ^1.1.0?

I'd submit a pull request, but I don't see a vinyl v0.* branch - is vinyl v0.* no longer maintained or supported?

**Comment by phated** [comment]
@gilly3 nope, I recommend you just depend directly on a new version of vinyl-fs

**Pull request merged**
